version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:8080"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SqlServerConnection=Server=host.docker.internal,1433;Database=KatanaDB;User Id=sa;Password=Admin00!S;TrustServerCertificate=True;
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - katana-network
    volumes:
      - ./logs:/app/logs

  # DB servisleri kaldırıldı - host SQL Server kullanılıyor

networks:
  katana-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local
